const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("aidev", {
  getState: () => ipcRenderer.invoke("app:getState"),
  saveSettings: (settings) => ipcRenderer.invoke("settings:save", settings),
  saveConfig: (config) => ipcRenderer.invoke("config:save", config),
  saveBudget: (budget) => ipcRenderer.invoke("budget:save", budget),
  openProject: () => ipcRenderer.invoke("workspace:openProject"),
  newProject: () => ipcRenderer.invoke("workspace:newProject"),
  createScratchProject: () => ipcRenderer.invoke("workspace:createScratchProject"),
  switchProject: (root) => ipcRenderer.invoke("workspace:switchProject", root),
  removeProject: (root) => ipcRenderer.invoke("workspace:removeProject", root),
  refreshProjectSummary: (root) => ipcRenderer.invoke("workspace:refreshProjectSummary", root),
  supervisor: (payload) => ipcRenderer.invoke("run:supervisor", payload),
  supervisorAnalyze: (payload) => ipcRenderer.invoke("run:supervisor-analyze", payload),
  direct: (payload) => ipcRenderer.invoke("run:direct", payload),
  stop: () => ipcRenderer.invoke("run:stop"),
  init: () => ipcRenderer.invoke("workspace:init"),
  listRuns: () => ipcRenderer.invoke("runs:list"),
  readRun: (runId) => ipcRenderer.invoke("run:read", runId),
  undoRun: (runId) => ipcRenderer.invoke("run:undo", runId),
  validateRun: (runId) => ipcRenderer.invoke("run:validate", runId),
  rebuildProjectIndex: () => ipcRenderer.invoke("project:index"),
  diagnostics: () => ipcRenderer.invoke("app:diagnostics"),
  lmStudioModels: (url) => ipcRenderer.invoke("models:lmstudio", url),
  openPath: (target) => ipcRenderer.invoke("path:open", target),
  pickAttachments: () => ipcRenderer.invoke("attachments:pick"),
  terminalHistory: () => ipcRenderer.invoke("terminal:history"),
  runTerminal: (payload) => ipcRenderer.invoke("terminal:run", payload),
  stopTerminal: () => ipcRenderer.invoke("terminal:stop"),
  pickTerminalCwd: (currentPath) => ipcRenderer.invoke("terminal:pickCwd", currentPath),
  onProcessStart: (callback) => ipcRenderer.on("process-start", (_event, value) => callback(value)),
  onProcessOutput: (callback) => ipcRenderer.on("process-output", (_event, value) => callback(value)),
  onProcessHeartbeat: (callback) => ipcRenderer.on("process-heartbeat", (_event, value) => callback(value)),
  onProcessFinish: (callback) => ipcRenderer.on("process-finish", (_event, value) => callback(value)),
  onProcessError: (callback) => ipcRenderer.on("process-error", (_event, value) => callback(value)),
  onTerminalStart: (callback) => ipcRenderer.on("terminal-start", (_event, value) => callback(value)),
  onTerminalOutput: (callback) => ipcRenderer.on("terminal-output", (_event, value) => callback(value)),
  onTerminalFinish: (callback) => ipcRenderer.on("terminal-finish", (_event, value) => callback(value)),
  onTerminalError: (callback) => ipcRenderer.on("terminal-error", (_event, value) => callback(value)),
});
